module.exports = {
  PAGE_ACESS_TOKEN: process.env.TOKEN_LANA_MESSENGER_BOT,
  VERIFY_TOKEN: process.env.TOKEN_LANA_MESSENGER_BOT_VERIFY,
  APP_SECRET: process.env.TOKEN_LANA_MESSENGER_BOT_APP_SECRET,
  LANA_API_KEY : process.env.lana_API_MASTER_KEY,
  URL_MESSAGE_ENDPOINT: process.env.URL_MESSENGER_ENDPOINT
};
